version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    groups:
      prod-deps:
        dependency-type: production
      dev-deps:
        dependency-type: development
    ignore:
      - dependency-name: "@babel/core"
        versions: [">=8"]
      - dependency-name: "@babel/plugin-transform-class-properties"
        versions: [">=8"]
      - dependency-name: "@babel/plugin-transform-private-methods"
        versions: [">=8"]
      - dependency-name: "@babel/preset-env"
        versions: [">=8"]
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      gh-actions:
        update-types:
          - "major"
    schedule:
      interval: "weekly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"